import "@mantine/core/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";
import { TodoProvider } from "config/TodoContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <MantineProvider>
          <TodoProvider>
            <Suspense fallback={<div>loading....</div>}>{children}</Suspense>
          </TodoProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
